### ISSUE TITLE
Branch: Webinar Fatal error: Class 'Jtl\Connector\Core\Connector\CoreConnector' not found

### ISSUE THREAD

**Issue by gstrainovic** [jtl-software/connector-example#1]
Hallo Zusammen

Was mache ich falsch?
![grafik](https://user-images.githubusercontent.com/8936333/87972344-020e0f80-cac7-11ea-91d6-843d5067d5d7.png)

Vielleicht sollte man lieber eine stabile Version des Core verwenden, statt dev-develop?
Falls ja, mit welcher Version soll ich es probieren?
![grafik](https://user-images.githubusercontent.com/8936333/87972515-4ef1e600-cac7-11ea-8ea8-700894b5e2db.png)

**Comment by gstrainovic** [comment]
Connector Core wurde ev. auf dem Dev. Branch entfernt:

https://github.com/jtl-software/connector-core/commit/fc5bce6a6be1d11815fbe5ba5b300197d57573a3#diff-f055db8d4ab4b213ac54feb3fef4ad37

**Comment by drieschel** [comment]
Hallo @gstrainovic,

das Webinar diente dazu den in der Entwicklung befindlichen Connector Core (Version 4) vorzustellen, daher der Develop Branch. Es hat sich allerdings in der Zwischenzeit noch einiges im Develop Branch des Connector Core getan. Daher passt der Content aus dem Webinar nicht mehr ganz mit dem Stand des Develop Branches überein. Wenn du erstmal lernen möchtest wie ein Connector grundsätzlich funktioniert, würde ich dir daher empfehlen auf den aktuellen Master Branch des Beispiel Connectors zu setzen, in Verbindung mit der unter folgendem Link zu findenden Dokumentation: https://jtl-devguide.readthedocs.io/projects/jtl-connector/en/latest/example/index.html - Passend dazu solltest du den Connector Core entweder in Version 2.7 oder 3.1 einsetzen. Die beiden Branches unterscheiden sich aktuell fast gar nicht voneinander.

**Comment by gstrainovic** [comment]
Hallo Immauel @drieschel 

Verstehe, danke für die Antwort.

Beim Master Branch kann ich aufgrund des fehlenden Identify keine Verbindung zum Wawi herstellen. Bei Master zwar mit dem Tester Tool aber nicht mit Wawi. Im Webinar sah ich das du WaWi benutzt hast. Also hat der Webinar Branch im Vergleich zum Master Branch einen Identify? 
Ich bin ein JTL Connector Anfänger, mir würde es sehr helfen wenn der Master eine Identify hätte für Wawi. Könnt ihr im Master oder eine Branch den Identify integrieren? Falls nein wird in einem Video oder Doku beschrieben wie man selber einen Identify programmiert?

Gruss Goran

**Comment by drieschel** [comment]
Hallo @gstrainovic,

schau mal in https://github.com/jtl-software/connector-example/blob/master/src/Controller/Connector.php. Dort liegt die Identify Methode.

**Comment by gstrainovic** [comment]
Ok, ich hab was wie es aussieht was durcheinander gebraucht, Identify funktioniert doch auch beim Master von connector-example.

Danke für deine Hilfe!  👍

**Comment by drieschel** [comment]
Zur Ergänzung: Im neuen Core (Develop Branch) muss keine Identify Methode mehr implementiert werden. Es müssen dafür nur noch 3 Methoden (getPlatformName, getPlatformVersion, getEndpointVersion) in einer Klasse definiert werden, die das ConnectorInterface implementiert.
