### ISSUE TITLE
Some errors under PHP 8.x

### ISSUE THREAD

**Issue by sdunger** [jtl-software/connector-example#11]
PHP 8.x:

Fatal error: Declaration of Jtl\Connector\Core\Http\JsonResponse::setLogger(Psr\Log\LoggerInterface $logger) must be compatible with Psr\Log\LoggerAwareInterface::setLogger(Psr\Log\LoggerInterface $logger): void in jtlconnector/vendor/jtl/connector/src/Http/JsonResponse.php on line 75

**Comment by Platzke-jtl** [comment]
This is Fixed in newer Connector Core Releases
