### ISSUE TITLE
Parenthesis error

### ISSUE THREAD

**Issue by sPooKee** [jtl-software/connector-example#2]
https://github.com/jtl-software/connector-example/blob/898475c472010be2a01e3cd31b31fd19acbf2845/src/Mapper/PrimaryKeyMapper.php#L88

Sollte wohl so lauten:

```php
return $this->db->query(sprintf('DELETE FROM mapping %s', $where));
```

**Comment by drieschel** [comment]
Hallo @sPooKee,

danke für den Hinweis. Der Fehler wurde soeben korrigiert.
