### ISSUE TITLE
Error 0 - Undefined constant "Jtl\Connector\Core\Database\SQLITE3_OPEN_READWRITE"

### ISSUE THREAD

**Issue by ADSiga** [jtl-software/connector-example#5]
Ich habe diesen Fehler erhalten, nachdem ich die PHP-Version auf 8.0.6 aktualisiert habe. Obwohl ich ext-sqlite3 in der composer.json hinzugefügt habe, hat das überhaupt nicht geholfen. 
Wenn ich versuche, 'use SQLite3;' hinzuzufügen, würde es nicht funktionieren, weil die Klasse SQLite3 nicht neu deklariert werden kann...
Was kann ich tun?

**Comment by drieschel** [comment]
Hallo @ADSiga,

versuche es bitte einmal mit der kürzlich veröffentlichten Connector Core Version 4.1.1.
